// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyAhECreC30AunnMGZct47k_2CNiAOIW97I',
    appId: '1:775511309581:web:79db6281682783cff10444',
    messagingSenderId: '775511309581',
    projectId: 'store-app-3be10',
    authDomain: 'store-app-3be10.firebaseapp.com',
    storageBucket: 'store-app-3be10.appspot.com',
    measurementId: 'G-97YJG7TFLZ',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyDUpSXH2sscIex4ohXgfrO9mqdFos2Qq9w',
    appId: '1:775511309581:android:6be10b083f5d3420f10444',
    messagingSenderId: '775511309581',
    projectId: 'store-app-3be10',
    storageBucket: 'store-app-3be10.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyCM7DNYMMuPkYLOTb84Kwwue4WnG7uB1j0',
    appId: '1:775511309581:ios:e80d97808ff50f8ff10444',
    messagingSenderId: '775511309581',
    projectId: 'store-app-3be10',
    storageBucket: 'store-app-3be10.appspot.com',
    iosClientId: '775511309581-ug3kaqv6nfcras03qh6620bro9ge1ahi.apps.googleusercontent.com',
    iosBundleId: 'com.example.store',
  );
}
